### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by innawe** [YuLin12345/Sneaker-Notify#1]
Hello! Thanks for Your work! I've followed the instructions but when i launch main.py i have the following error
![schermata 2017-03-13 alle 13 35 25](https://cloud.githubusercontent.com/assets/20047821/23854607/5d8c831e-07f2-11e7-9555-5d2f38e0afdf.png)

**Comment by YuLin12345** [comment]
Thanks for the interest in my code. Did you make a sneaker_spider folder and put all the files in there? I ran mine on Windows. If needed, I will take a look later for Mac.

**Comment by innawe** [comment]
Thanks for Your reply! Yes i try to use it on mac. Where i have to make the sneaker-spider folder? Thanks!

**Comment by YuLin12345** [comment]
Anywhere, just make sure the folder name is sneaker_spider or if you want you can follow me on twitter W_Notify I have it running on there.

**Comment by innawe** [comment]
I add the folder but i've got same error. I've just followed You on Twitter 

Inviato da iPhone
