### ISSUE TITLE
was working, now isnt

### ISSUE THREAD

**Issue by joshszn** [YuLin12345/Sneaker-Notify#10]
getting these errors as well
![beb8eff8d186dde650176467c84950bc](https://user-images.githubusercontent.com/27407488/31369399-26105e28-ad52-11e7-89fd-e41e722a3789.png)

**Comment by Alecazo** [comment]
Side note: Would also like a fix for this.

Thanks
Alec

**Comment by YuLin12345** [comment]
@Alecazo @joshszn Try restarting it, if you get something like above. Some sites are broken. Ill try to have it fix in the coming days.

Thanks
