### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by quantumcept** [YuLin12345/Sneaker-Notify#11]
I am noticing a memory leak. The script with run for a few hours until memory runs out. Do you know what is causing the leak? Fairly new to debugging scrapy.

**Comment by YuLin12345** [comment]
I would recommend splitting up the crawling into different servers. If you crawl everything on one server. It might be too much for the server to handle, it does have over 100 sites.

Thanks

**Comment by quantumcept** [comment]
I've minimized the number of sites to 13 and the amount of system memory used climbs every hour until the system runs out. Is there something else I can do?

**Comment by YuLin12345** [comment]
@quantumcept Make sure you have the latest code. Also, try commenting out KithSpider for now. I think that might be the one causing memory to run out.

Thanks, let me know how it goes.

**Comment by quantumcept** [comment]
Ok, its been running for 12+ hours now, and the memory is staying constant. I think it really was KithSpider causing memory to run out.  Thanks so much!
