### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by lello98** [YuLin12345/Sneaker-Notify#12]
Hi i haven t understood how to configure discord monitor with the webhooks could you help me?

**Comment by YuLin12345** [comment]
https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks

After you have that URL go to mysql_pipeline.py

Edit 
requests.post('**DISCORD WEBHOOK URL**', data={'content': "**" + item['name'] + "**" + "\n" + item['link'] + "\n" + "\n" + "[ATC]: " + item['size'] + "\n" + "\n"})

Thanks
