### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by trvpbo0om** [YuLin12345/Sneaker-Notify#14]
when I try to install SQL I get this error 

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/43/mk2nqj292fn50__zjy36_8900000gn/T/pip-build-XtKZhv/MySQL-python/

**Comment by YuLin12345** [comment]
What OS you running on??

**Comment by trvpbo0om** [comment]
osx high Sierra
