### ISSUE TITLE
can i get some help

### ISSUE THREAD

**Issue by camron114** [YuLin12345/Sneaker-Notify#16]
CRITICAL: KithSpider STARTED.
CRITICAL: RuvillaSpider STARTED.
CRITICAL: FootShopSpider STARTED.
CRITICAL: AfewSpider STARTED.
CRITICAL: CalirootsSpider STARTED.
CRITICAL: EinhalbSpider STARTED.
CRITICAL: TintSpider STARTED.
CRITICAL: OverkillSpider STARTED.
CRITICAL: FootDistrictSpider STARTED.
CRITICAL: SizeSpider STARTED.
CRITICAL: YCMCSpider STARTED.
CRITICAL: CitySpider STARTED.
CRITICAL: FootLockerSpider STARTED.
CRITICAL: FootActionSpider STARTED.
CRITICAL: ChampsSpider STARTED.
CRITICAL: EastBaySpider STARTED.
CRITICAL: AdidasUSSpider STARTED.
CRITICAL: AdidasEUSpider STARTED.
CRITICAL: NikeSpider STARTED.
CRITICAL: NordstromSpider STARTED.
CRITICAL: JDSportsSpider STARTED.
CRITICAL: FootPatrolSpider STARTED.
CRITICAL: SneakerPoliticsSpider STARTED.
CRITICAL: UrbanIndustrySpider STARTED.
CRITICAL: SneakerBaasSpider STARTED.
CRITICAL: UrbanOutfittersSpider STARTED.
CRITICAL: LuisaSpider STARTED.
CRITICAL: SlamJamSpider STARTED.
CRITICAL: Rise45Spider STARTED.
CRITICAL: UndefeatedSpider STARTED.
CRITICAL: ZapposSpider STARTED.
CRITICAL: PointzSpider STARTED.
CRITICAL: StickABushSpider STARTED.
CRITICAL: KongSpider STARTED.
CRITICAL: SaveOurSoleSpider STARTED.
CRITICAL: InflammableSpider STARTED.
CRITICAL: DefShopSpider STARTED.
CRITICAL: OffspringSpider STARTED.
CRITICAL: SoleKitchenSpider STARTED.
CRITICAL: DromeSpider STARTED.
CRITICAL: FootAsylumSpider STARTED.
CRITICAL: ConceptsSpider STARTED.
CRITICAL: SocialStatusSpider STARTED.
CRITICAL: ExtraButterSpider STARTED.
CRITICAL: BodegaSpider STARTED.
CRITICAL: SaintAlfredSpider STARTED.
CRITICAL: LapstoneNHammerSpider STARTED.
CRITICAL: ShelfLifeSpider STARTED.
CRITICAL: AsphaltGoldSpider STARTED.
CRITICAL: HanonSpider STARTED.
CRITICAL: SoleBoxSpider STARTED.
CRITICAL: ConsortiumSpider STARTED.
CRITICAL: HavenSpider STARTED.
CRITICAL: NeedSupplySpider STARTED.
CRITICAL: LoadedSpider STARTED.
CRITICAL: WellGoshSpider STARTED.
CRITICAL: CapsuleSpider STARTED.
CRITICAL: YMESpider STARTED.
CRITICAL: HypeDCSpider STARTED.
CRITICAL: BSTNSpider STARTED.
CRITICAL: TrophyRoomSpider STARTED.
CRITICAL: OfficeSpider STARTED.
CRITICAL: ALLikeSpider STARTED.
CRITICAL: UrbanJungleSpider STARTED.
CRITICAL: SSenseSpider STARTED.
CRITICAL: BackDoorSpider STARTED.
CRITICAL: BasketSpider STARTED.
CRITICAL: DopeFactorySpider STARTED.
CRITICAL: NextDoorSpider STARTED.
CRITICAL: SummerSpider STARTED.
CRITICAL: MrPorterSpider STARTED.
CRITICAL: StormFashionSpider STARTED.
CRITICAL: TresBienSpider STARTED.
CRITICAL: PackerSpider STARTED.
CRITICAL: AddictSpider STARTED.
CRITICAL: AphroditeSpider STARTED.
CRITICAL: BaitSpider STARTED.
CRITICAL: BlendsSpider STARTED.
CRITICAL: NiceKicksSpider STARTED.
CRITICAL: FeatureSpider STARTED.
CRITICAL: HypeBeastSpider STARTED.
CRITICAL: DeadStockSpider STARTED.
CRITICAL: NotreSpider STARTED.
CRITICAL: NrmlSpider STARTED.
CRITICAL: OnenessSpider STARTED.
CRITICAL: PufferRedsSpider STARTED.
CRITICAL: RenartsSpider STARTED.
CRITICAL: ProperSpider STARTED.
CRITICAL: SoleStopSpider STARTED.
CRITICAL: TitoloSpider STARTED.
CRITICAL: UptownSpider STARTED.
CRITICAL: WestNYCSpider STARTED.
CRITICAL: XileClothingSpider STARTED.
CRITICAL: SoleflySpider STARTED.
CRITICAL: SVDSpider STARTED.
CRITICAL: HubbastilleSpider STARTED.
CRITICAL: KithSpider STARTED.
CRITICAL: RuvillaSpider STARTED.
CRITICAL: FootShopSpider STARTED.
CRITICAL: AfewSpider STARTED.
CRITICAL: CalirootsSpider STARTED.
CRITICAL: EinhalbSpider STARTED.
CRITICAL: TintSpider STARTED.
CRITICAL: OverkillSpider STARTED.
CRITICAL: FootDistrictSpider STARTED.
CRITICAL: SizeSpider STARTED.
CRITICAL: YCMCSpider STARTED.
CRITICAL: CitySpider STARTED.
CRITICAL: FootLockerSpider STARTED.
CRITICAL: FootActionSpider STARTED.
CRITICAL: ChampsSpider STARTED.
CRITICAL: EastBaySpider STARTED.
CRITICAL: AdidasUSSpider STARTED.
CRITICAL: AdidasEUSpider STARTED.
CRITICAL: NikeSpider STARTED.
CRITICAL: NordstromSpider STARTED.
CRITICAL: JDSportsSpider STARTED.
CRITICAL: FootPatrolSpider STARTED.
CRITICAL: SneakerPoliticsSpider STARTED.
CRITICAL: UrbanIndustrySpider STARTED.
CRITICAL: SneakerBaasSpider STARTED.
CRITICAL: UrbanOutfittersSpider STARTED.
CRITICAL: LuisaSpider STARTED.
CRITICAL: SlamJamSpider STARTED.
CRITICAL: Rise45Spider STARTED.
CRITICAL: UndefeatedSpider STARTED.
CRITICAL: ZapposSpider STARTED.
CRITICAL: PointzSpider STARTED.
CRITICAL: StickABushSpider STARTED.
CRITICAL: KongSpider STARTED.
CRITICAL: SaveOurSoleSpider STARTED.
CRITICAL: InflammableSpider STARTED.
CRITICAL: DefShopSpider STARTED.
CRITICAL: OffspringSpider STARTED.
CRITICAL: SoleKitchenSpider STARTED.
CRITICAL: DromeSpider STARTED.
CRITICAL: FootAsylumSpider STARTED.
CRITICAL: ConceptsSpider STARTED.
CRITICAL: SocialStatusSpider STARTED.
CRITICAL: ExtraButterSpider STARTED.
CRITICAL: BodegaSpider STARTED.
CRITICAL: SaintAlfredSpider STARTED.
CRITICAL: LapstoneNHammerSpider STARTED.
CRITICAL: ShelfLifeSpider STARTED.
CRITICAL: AsphaltGoldSpider STARTED.
CRITICAL: HanonSpider STARTED.
CRITICAL: SoleBoxSpider STARTED.
CRITICAL: ConsortiumSpider STARTED.
CRITICAL: HavenSpider STARTED.
CRITICAL: NeedSupplySpider STARTED.
CRITICAL: LoadedSpider STARTED.
CRITICAL: WellGoshSpider STARTED.
CRITICAL: CapsuleSpider STARTED.
CRITICAL: YMESpider STARTED.
CRITICAL: HypeDCSpider STARTED.
CRITICAL: BSTNSpider STARTED.
CRITICAL: TrophyRoomSpider STARTED.
CRITICAL: OfficeSpider STARTED.
CRITICAL: ALLikeSpider STARTED.
CRITICAL: UrbanJungleSpider STARTED.
CRITICAL: SSenseSpider STARTED.
CRITICAL: BackDoorSpider STARTED.
CRITICAL: BasketSpider STARTED.
CRITICAL: DopeFactorySpider STARTED.
CRITICAL: NextDoorSpider STARTED.
CRITICAL: SummerSpider STARTED.
CRITICAL: MrPorterSpider STARTED.
CRITICAL: StormFashionSpider STARTED.
CRITICAL: TresBienSpider STARTED.
CRITICAL: PackerSpider STARTED.
CRITICAL: AddictSpider STARTED.
CRITICAL: AphroditeSpider STARTED.
CRITICAL: BaitSpider STARTED.
CRITICAL: BlendsSpider STARTED.
CRITICAL: NiceKicksSpider STARTED.
CRITICAL: FeatureSpider STARTED.
CRITICAL: HypeBeastSpider STARTED.
CRITICAL: DeadStockSpider STARTED.
CRITICAL: NotreSpider STARTED.
CRITICAL: NrmlSpider STARTED.
CRITICAL: OnenessSpider STARTED.
CRITICAL: PufferRedsSpider STARTED.
CRITICAL: RenartsSpider STARTED.
CRITICAL: ProperSpider STARTED.
CRITICAL: SoleStopSpider STARTED.
CRITICAL: TitoloSpider STARTED.
CRITICAL: UptownSpider STARTED.
CRITICAL: WestNYCSpider STARTED.
CRITICAL: XileClothingSpider STARTED.
CRITICAL: SoleflySpider STARTED.
CRITICAL: SVDSpider STARTED.
CRITICAL: HubbastilleSpider STARTED.

i got this far i dont know if its working or not why the dev didnt put a better read me smh

**Comment by YuLin12345** [comment]
If you get alerts = working
If not = not working
