### ISSUE TITLE
SQL database. how do i properly use crawler.sql? please help

### ISSUE THREAD

**Issue by trvpbo0om** [YuLin12345/Sneaker-Notify#17]
the database is definitely my problem please help

![capture1](https://user-images.githubusercontent.com/34948870/34651895-f28e6344-f3a4-11e7-9e20-a3ae064bdda3.PNG)

![capture2](https://user-images.githubusercontent.com/34948870/34651927-94139f90-f3a5-11e7-8787-bdef8451987d.PNG)

![capture](https://user-images.githubusercontent.com/34948870/34651896-f58098ce-f3a4-11e7-8792-0cf4b3c0884f.PNG)

**Comment by trvpbo0om** [comment]
i did it!!!!!! fuck you dev lol jk butplease update your readme so we dont bother you

**Comment by LMascher** [comment]
What did you do to fix it? Also have a discord? I need some more help and dev isnt responding to me
