### ISSUE TITLE
Problem: connection lost to some websites

### ISSUE THREAD

**Issue by Cita98** [YuLin12345/Sneaker-Notify#18]
![immagine1](https://user-images.githubusercontent.com/35450297/34936689-a63029f8-f9e2-11e7-932d-ec1ad6483faf.jpg)
![immagine2](https://user-images.githubusercontent.com/35450297/34936692-a8e864c6-f9e2-11e7-95db-c4c89a1540b6.jpg)

Hi YuLin!
i am having some issues connecting to some websites, any idea how to solve this?
i would also like to ask you, are the websites marked as "STARTED" working? do i need to leave this program open on my pc in order to get notifications on discord?
thanks in advance for you work!

**Comment by YuLin12345** [comment]
Check if your:

1) Banned from the site.
2) Restart and see if it still happens. Sometime it closes when you crawl for too long.

Thanks.
