### ISSUE TITLE
error while installing mySQL-python on mac

### ISSUE THREAD

**Issue by jl361** [YuLin12345/Sneaker-Notify#2]
I am on mac os sierra 10.12.4 and have installed python v2.7.13. I have installed all requirements within the zip folder but..

I am trying to set up the monitor and am getting this error:

$ pip install MySQL-python
Collecting MySQL-python
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/b1/m87hc8_x7rq2_5l9rnl7ngrm0000gn/T/pip-build-NCs9F1/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 53, in get_config
        libraries = [ dequote(i[2:]) for i in libs if i.startswith(compiler_flag("l")) ]
      File "setup_posix.py", line 8, in dequote
        if s[0] in "\"'" and s[0] == s[-1]:
    IndexError: string index out of range
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/b1/m87hc8_x7rq2_5l9rnl7ngrm0000gn/T/pip-build-NCs9F1/MySQL-python/

**Comment by felixthechef** [comment]
got the same issue.

**Comment by YuLin12345** [comment]
For Mac: to install MySQL-python. Open terminal and type the below:

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install mysql-connector-c
pip install MySQL-python

See if that works.

**Comment by trvpbo0om** [comment]
this didn't work for me still getting 

ACGDeptordsiMac:main acgdeptford$ pip install MySQL-python
Collecting MySQL-python
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/43/mk2nqj292fn50__zjy36_8900000gn/T/pip-build-ODIk2d/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 53, in get_config
        libraries = [ dequote(i[2:]) for i in libs if i.startswith(compiler_flag("l")) ]
      File "setup_posix.py", line 8, in dequote
        if s[0] in "\"'" and s[0] == s[-1]:
    IndexError: string index out of range
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/43/mk2nqj292fn50__zjy36_8900000gn/T/pip-build-ODIk2d/MySQL-python/

**Comment by tede12** [comment]
Same error...
