### ISSUE TITLE
Tweet Embeded Message

### ISSUE THREAD

**Issue by leoszn** [YuLin12345/Sneaker-Notify#23]
Hi YuLin, 

https://camo.githubusercontent.com/97c3d0e956146c5986c52872f1bedcf9bf55cc50/687474703a2f2f692e696d6775722e636f6d2f637149327330782e706e67

How can I tweet it with it with the box image? I was unable to tweet it with the second one, but It keeps tweet with the first one without box image

**Comment by YuLin12345** [comment]
Some sites has preview enabled while some don't. Nothing you can really do. Unless you crawl for the image and add it onto the message.
