### ISSUE TITLE
installing the MySQL database

### ISSUE THREAD

**Issue by epicsurf5200** [YuLin12345/Sneaker-Notify#24]
I'm a little confused on step 3 of the read me. There is no file in the main folder named MySQL database are you referring to the crawler.sql? If this code works I plan to donate! thank you

**Comment by epicsurf5200** [comment]
figured it out!

**Comment by YuLin12345** [comment]
Okay, cool.

**Comment by LMascher** [comment]
Yo how did u figure it out? What did you do?
