### ISSUE TITLE
Still unable to download MySQL_Python

### ISSUE THREAD

**Issue by LMascher** [YuLin12345/Sneaker-Notify#27]
Hey, thank you for this open sourced project. Also, I am still unable to install MySQL_Python, I think I am putting it in my python folder wrong from the download link provided. Any advice? Also, how do I find the SQL Database? it is not included in the folder

**Comment by tede12** [comment]
Check this [click here](https://stackoverflow.com/questions/51123044/pip-install-mysql-python) then It works.
