### ISSUE TITLE
Get caught up on same line when I try to run main.py

### ISSUE THREAD

**Issue by LMascher** [YuLin12345/Sneaker-Notify#28]
Hey, when I try to run main.py in cmd, it gets caught up on this line: 
process = CrawlerProcess(settings=crawler_settings)
Here is the error code: 
![image](https://user-images.githubusercontent.com/40897942/42414035-186bee44-81fb-11e8-9b44-a9a3acf47ef6.png)

**Comment by YuLin12345** [comment]
Try reinstalling everything and re-download the files from develop tree.
