### ISSUE TITLE
Enabling Caching

### ISSUE THREAD

**Issue by quantumcept** [YuLin12345/Sneaker-Notify#3]
Quick question, how come enabling http caching only scrapes the websites once and doesn't rescrape after that. I am trying to enable caching to save some bandwidth. 

Here is my what I added to my settings.py

```
HTTPCACHE_ENABLED = True
HTTPCACHE_EXPIRATION_SECS = 0
HTTPCACHE_DIR = 'httpcache'
HTTPCACHE_IGNORE_HTTP_CODES = []
HTTPCACHE_STORAGE = 'scrapy.extensions.httpcache.FilesystemCacheStorage'
HTTPCACHE_POLICY = 'scrapy.extensions.httpcache.DummyPolicy'
```

**Comment by YuLin12345** [comment]
I am not sure. You would need to check the scrapy documentation,
