### ISSUE TITLE
Issue With MySQL

### ISSUE THREAD

**Issue by thecoolhascome** [YuLin12345/Sneaker-Notify#4]
Hello, First off i would like to say thank you for putting the time and work into making this monitor. 

I am having an issue getting this to work. I have created a MySQL Database with AWS and i have a seperate server on AWS. I put the endpoint as the host and when i run everything seems to work fine as it will say "Kith Spider Started" and then it will run through some errors like this
<img width="1234" alt="screen shot 2017-07-25 at 1 25 08 am" src="https://user-images.githubusercontent.com/28245871/28557204-031d5a8e-70d9-11e7-8300-d821ce463da1.png">
I am not sure why i am getting this issue/if i am doing something wrong with mysql etc

all help would be appreciated.

Also, DM me on twitter @netwxrking sometime soon as i would love to discuss something!

**Comment by YuLin12345** [comment]
Probably the AWS MySQL Server needs authentication of the ip address you are trying to access it on - For security purposes.
