### ISSUE TITLE
Issue With Scrapy

### ISSUE THREAD

**Issue by thecoolhascome** [YuLin12345/Sneaker-Notify#5]
Hello, I recently fixed and figured out the MySQL Issue - I have had all spiders start and now i got this issue:

<img width="1538" alt="screen shot 2017-07-25 at 12 19 45 pm" src="https://user-images.githubusercontent.com/28245871/28582504-9fa4397c-7133-11e7-84d3-b76fae913690.png">

Thanks In Advance!

**Comment by YuLin12345** [comment]
Try re-starting it again and let me know if the error is still there.

**Comment by thecoolhascome** [comment]
Hello, I tried restarting it and i still have this same error which reads


[scrapy.downloadermiddlewares.robotstxt] ERROR: Error downloading <GET https://www.back-door.it/robots.txt>: [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]
ResponseNeverReceived: [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]
2017-07-25 23:09:11 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.back-door.it/product-category/sneakers/page/1/?orderby=date>: [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]

**Comment by Bleez103** [comment]
*OFF TOPIC*

Would it be possible to add Slack support? @YuLin12345

**Comment by YuLin12345** [comment]
@Bleez103 Go to pipeline.py, paste in Slack Webhook URL instead of Discord's, and see if it works. Discord and Slack should be similar.

requests.post(' DISCORD WEBHOOK URL ', data={'content': TEXT_TO_TWEET})
