### ISSUE TITLE
Prevent script from tweeting same item on site x

### ISSUE THREAD

**Issue by AL3XAND3R98** [YuLin12345/Sneaker-Notify#6]
Is there anyway for it to locally store or somehow store already processed/tweeted so if script is restarted or something it doesnt re-tweet the same Items. Thanks.

**Comment by YuLin12345** [comment]
That is the point of the database (MySQL). If the item is already processed it will not retweet it unless they changed the URL link or you remove the data from the database.

**Comment by Bleez103** [comment]
@YuLin12345  -- I'm not too sure if it's something I've done wrong on my end, but it appears that the same few sites sending updates of the same items over and over.

![image](https://user-images.githubusercontent.com/25425376/29441827-c0fe9476-8382-11e7-8b3e-917774185317.png)

**Comment by YuLin12345** [comment]
@Bleez103 you sure the database it working??

**Comment by Bleez103** [comment]
@YuLin12345  I'm not too sure. Should I reload the database?

**EDIT**  Reloaded the Database and its appears all is well. No dupe announcements are happening now and announcing new products as they arrive.

**Comment by YuLin12345** [comment]
@Bleez103 Great! I figured it's something related with the database.
