### ISSUE TITLE
Unknown Database

### ISSUE THREAD

**Issue by AmielG12** [YuLin12345/Sneaker-Notify#7]
After installing MySQL and running the database, i still keep getting this error. Could you help me out with it?
![image](https://user-images.githubusercontent.com/15823047/29986912-ce3d23d4-8f65-11e7-8e3b-9a211fc218fb.png)

**Comment by YuLin12345** [comment]
@AmielG12 Did you make a database called 'crawler' with the .SQL file imported?

Thanks
