### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by Bleez103** [YuLin12345/Sneaker-Notify#8]
I'm not too sure if this is being caused on my end, but after the script has ran for a while I start to see these messages in the terminal.
2017-09-03 21:35:34 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.featuresneakerboutique.com/collectio
ns/footwear?page=1&sort_by=created-descending>: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost:
Connection to the other side was lost in a non-clean fashion: Connection lost.>]

2017-09-03 21:36:03 [scrapy.core.scraper] ERROR: Error downloading <GET http://sneakerpolitics.com/collections/sneakers?
page=1>: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]

**Comment by YuLin12345** [comment]
@Bleez103 Sorry for the late reply. Check if your banned on the site. If not, just restart the script.

Thanks

**Comment by Bleez103** [comment]
@YuLin12345 .. No worries. I can still access the websites from the server manually, so I guess I'll need to load proxies to avoid this issue.

Thanks again as always.
