### ISSUE TITLE
was working, but now seems to have stopped

### ISSUE THREAD

**Issue by joshszn** [YuLin12345/Sneaker-Notify#9]
not sure whats causing this.
Was working fine earlier.
Restarted and still gives this error and doesn't tweet links.
![2441faa3275f9285916bcfdfdf7d3eb1](https://user-images.githubusercontent.com/27407488/31368129-c45dbaa2-ad49-11e7-94c7-6b46b23cf041.png)

**Comment by YuLin12345** [comment]
@joshszn They changed the html code on the site. Will need to re-edit the html xpath.

Thanks
